services:

  Apps.mooc.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.mooc.controllers.CoursePutController:
    class: ../../controllers/CoursePutController
    arguments: [""]

  Apps.mooc.controllers.TournamentPutController:
    class: ../../controllers/TournamentPutController
    arguments: ["@Tournament.application.TournamentCreator"]    
